In [1]:
import seaborn as sns
df = sns.load_dataset('diamonds')

In [2]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
df.drop(['depth', 'table', 'x', 'y', 'z'], axis=1, inplace=True)

In [4]:
df

       carat        cut color clarity  price
0       0.23      Ideal     E     SI2    326
1       0.21    Premium     E     SI1    326
2       0.23       Good     E     VS1    327
3       0.29    Premium     I     VS2    334
4       0.31       Good     J     SI2    335
...      ...        ...   ...     ...    ...
53935   0.72      Ideal     D     SI1   2757
53936   0.72       Good     D     SI1   2757
53937   0.70  Very Good     D     SI1   2757
53938   0.86    Premium     H     SI2   2757
53939   0.75      Ideal     D     SI2   2757

[53940 rows x 5 columns]

In [6]:
import pandas as pd

In [7]:
df = pd.get_dummies(df, drop_first=True)

In [8]:
import numpy as np
df['carat'] = np.log(1+df['carat'])
df['price'] = np.log(1+df['price'])

In [9]:
X = df.drop(columns="price")
y = df["price"]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
a = {"loss": ["squared_error", "epsilon_insensitive"],
"penalty": ["elasticnet"],
"alpha": np.logspace(-3, 3, 10),
"l1_ratio": np.linspace(0, 1, 10),
"learning_rate": ["constant"],
"eta0": np.logspace(-4, -1, 4)}

In [14]:
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import GridSearchCV

gr = GridSearchCV(
    estimator=SGDRegressor(),
    param_grid=a,
    scoring='neg_mean_squared_error',
    return_train_score=True,
    n_jobs=-1
)
gr.fit(X_train, y_train)

GridSearchCV(estimator=SGDRegressor(), n_jobs=-1,
             param_grid={'alpha': array([1.00000000e-03, 4.64158883e-03, 2.15443469e-02, 1.00000000e-01,
       4.64158883e-01, 2.15443469e+00, 1.00000000e+01, 4.64158883e+01,
       2.15443469e+02, 1.00000000e+03]),
                         'eta0': array([0.0001, 0.001 , 0.01  , 0.1   ]),
                         'l1_ratio': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
                         'learning_rate': ['constant'],
                         'loss': ['squared_error', 'epsilon_insensitive'],
                         'penalty': ['elasticnet']},
             return_train_score=True, scoring='neg_mean_squared_error')

In [15]:
gr.best_score_

-0.044991213231074786

In [28]:
Xn = 42
Xn_1 = 42
def func(x):
    return 24*x**2 - 4*x

def proiz_func(x):
    return 48*x - 4

while True:
    Xn_1 = Xn - func(Xn)/proiz_func(Xn)
    if np.abs(Xn_1 - Xn) < 0.0001:
        print(Xn_1)
        break
    print(Xn_1)
    
    Xn = Xn_1

21.041749502982107
10.562707090133793
5.323351550447383
2.7040050774153417
1.3949941413301903
0.7418109325525483
0.41784523900811205
0.26096925221473555
0.19169814030401197
0.16955770984744145
0.1667151339969682
0.1666666807529666

In [2]:
import numpy as np
from scipy.optimize import minimize

In [3]:
def func(x):
    return x[0]**2.0 + x[1]**2.0

In [4]:
def grad_func(x):
    return np.array([x[0] * 2, x[1] * 2])

In [5]:
x_0 = [1.0, 1.0]
result = minimize(func, x_0, method='BFGS', jac=grad_func)
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.5f' % (solution, evaluation))
 
#Статус оптимизации Optimization terminated successfully.
#Количество оценок: 3
#Решение: f([0. 0.]) = 0.00000

Статус оптимизации Optimization terminated successfully.
Количество оценок: 3
Решение: f([0. 0.]) = 0.00000

In [14]:
# определяем нашу функцию
def func(x):
    return x[0]**4 + 6*x[1]**2 + 10 
#  определяем градиент функции
def grad_func(x):
    return np.array([4*x[0]**3, 12*x[1]])
 
# определяем начальную точку
x_0 = [100, 100]
# реализуем алгоритм L-BFGS-B
result = minimize(func, x_0, method='BFGS', jac=grad_func)
# получаем результат
print('Статус оптимизации %s' % result['message'])
print('Количество оценок: %d' % result['nfev'])
solution = result['x']
evaluation = func(solution)
print('Решение: f(%s) = %.5f' % (solution, evaluation))

Статус оптимизации Optimization terminated successfully.
Количество оценок: 37
Решение: f([1.31617159e-02 6.65344582e-14]) = 10.00000