In [5]:
from sklearn.metrics import ndcg_score, dcg_score
import numpy as np

true = np.asarray([[3, 2, 1, 0, 0]])
relevance = np.asarray([[3, 2, 0, 0, 1]])

print(ndcg_score(true, relevance))

#0.980840401274087

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\user\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "c:\Users\user\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\user\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "c:\Users\user\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\Users\user\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\Users\user\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "c:\Users\user\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\user\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\user\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\user\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\user\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\user\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\user\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\user\AppData\Local\Temp\ipykernel_6388\3833489760.py", line 1, in <module>
    from sklearn.metrics import ndcg_score, dcg_score
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\__init__.py", line 70, in <module>
    from sklearn.base import clone  # noqa: E402
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py", line 20, in <module>
    from sklearn.utils._missing import is_pandas_na, is_scalar_nan
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\__init__.py", line 9, in <module>
    from sklearn.utils._chunking import gen_batches, gen_even_slices
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\_chunking.py", line 11, in <module>
    from sklearn.utils._param_validation import Interval, validate_params
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 17, in <module>
    from sklearn.utils.validation import _is_arraylike_not_scalar
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 24, in <module>
    from sklearn.utils._array_api import (
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py", line 20, in <module>
    from sklearn.utils.fixes import parse_version
  File "c:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\fixes.py", line 389, in <module>
    import pyarrow
  File "c:\Users\user\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

In [169]:
true = np.asarray([[2, 4, 1, 1, 1]])
predict = np.asarray([[2, 5, 2, 3, 1]])
print(ndcg_score(true, predict))

0.9748317848747132

In [198]:
import pandas as pd
movies = pd.read_csv(r'C:\Users\user\Desktop\Skilfactory\data1\movie.csv')
ratings = pd.read_csv(r'C:\Users\user\Desktop\Skilfactory\data1\dst-3.0_mathml_14_5_rating.csv')

In [199]:
df=pd.merge(ratings,movies, how='left',on='movieId')
df.head()

,userId,movieId,rating,timestamp,title,genres
0,1,2,3.5,2005-04-02 23:53:47,Jumanji (1995),Adventure|Children|Fantasy
1,1,29,3.5,2005-04-02 23:31:16,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
2,1,32,3.5,2005-04-02 23:33:39,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
3,1,47,3.5,2005-04-02 23:32:07,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,3.5,2005-04-02 23:29:40,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [200]:
df['title'].value_counts(normalize=True).head(5)

title
Pulp Fiction (1994)                 0.003365
Forrest Gump (1994)                 0.003309
Shawshank Redemption, The (1994)    0.003168
Silence of the Lambs, The (1991)    0.003165
Jurassic Park (1993)                0.002986
Name: proportion, dtype: float64

In [201]:
ser = pd.Series(df.groupby('title')['rating'].mean().sort_values(ascending=False))[:120]
ser.sort_index().tail(5)

title
Welcome to Australia (1999)                       5.0
When I Walk (2013)                                5.0
Who Killed Vincent Chin? (1987)                   5.0
Year Zero: The Silent Death of Cambodia (1979)    5.0
Yonkers Joe (2008)                                5.0
Name: rating, dtype: float64

In [202]:
df.groupby('title')['rating'].agg(['count', 'mean'])[df.groupby('title')['rating'].agg(['count', 'mean'])['count'] > 50].sort_values('mean', ascending=False)

                                     count      mean
title
Shawshank Redemption, The (1994)     63366  4.446990
Godfather, The (1972)                41355  4.364732
Usual Suspects, The (1995)           47006  4.334372
Schindler's List (1993)              50054  4.310175
Godfather: Part II, The (1974)       27398  4.275641
...                                    ...       ...
Barney's Great Adventure (1998)        419  1.163484
Glitter (2001)                         685  1.124088
Bratz: The Movie (2007)                180  1.105556
From Justin to Kelly (2003)            426  0.973005
SuperBabies: Baby Geniuses 2 (2004)    209  0.837321

[10472 rows x 2 columns]

In [255]:
articles_df = pd.read_csv(r'C:\Users\user\Desktop\Skilfactory\data1\shared_articles.csv')
articles_df = articles_df[articles_df['eventType'] == 'CONTENT SHARED']
articles_df.shape

(3047, 13)

In [256]:
interactions_df = pd.read_csv(r'C:\Users\user\Desktop\Skilfactory\data1\users_interactions.csv')

In [257]:
interactions_df.personId = interactions_df.personId.astype(str)
interactions_df.contentId = interactions_df.contentId.astype(str)
articles_df.contentId = articles_df.contentId.astype(str)

In [258]:
interactions_df.isnull().sum()

timestamp          0
eventType          0
contentId          0
personId           0
sessionId          0
userAgent      15394
userRegion     15405
userCountry    15394
dtype: int64

In [259]:
event_type = {
   'VIEW': 1.0,
   'LIKE': 2.0, 
   'BOOKMARK': 2.5, 
   'FOLLOW': 3.0,
   'COMMENT CREATED': 4.0,  
}

In [260]:
interactions_df['eventType'] = interactions_df['eventType'].map(event_type)
interactions_df['eventType'].mean(skipna=True)

1.2362885828078327

In [261]:
interactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72312 entries, 0 to 72311
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    72312 non-null  int64
 1   eventType    72312 non-null  float64
 2   contentId    72312 non-null  object
 3   personId     72312 non-null  object
 4   sessionId    72312 non-null  int64
 5   userAgent    56918 non-null  object
 6   userRegion   56907 non-null  object
 7   userCountry  56918 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 4.4+ MB

In [262]:
users_interactions_count_df = (
    interactions_df
    .groupby(['personId', 'contentId'])
    .first()
    .reset_index()
    .groupby('personId').size())

users_with_enough_interactions_df = \
    users_interactions_count_df[users_interactions_count_df >= 5].reset_index()[['personId']]

print(len(users_with_enough_interactions_df))

1140

In [263]:
interactions_from_selected_users_df = interactions_df.loc[np.in1d(interactions_df.personId,
            users_with_enough_interactions_df)]
print(interactions_from_selected_users_df.shape)

(69868, 8)